## Creating ch7f RData object using function

## First, sourcing in 'posthoc_extract_chs.R'
#load("../output/mona_raw_outputs_100sim.RData")
#source("../code/posthoc_extract_chs.R")
load("mona_raw_outputs_100sim.RData") # for NeSI
source("posthoc_extract_chs.R") # for NeSI

## ch7f
encounterdat.ch7f = matrix(0, nrow=nrow(ch7f[,1,]), ncol=ncol(ch7f[,1,]))
for (i in 1:20) {
  encounterdat.ch7f = encounterdat.ch7f + ch7f[,i,]
}
ch7f.traploc = attributes(ch7f)$traps
xlim = c(0.5, 50.5)
ylim = c(0.5, 50.5)
data.ch7f = list(encounter.data = encounterdat.ch7f, trap.loc = ch7f.traploc, xlim = xlim, ylim = ylim, n.occasions = 20)

## ---------------------------------------------------------------------------------------

# Running the MCMC

## ---------------------------------------------------------------------------------------

# Libraries we need
library(nimble)
library(coda)
library(nimbleSCR)

# Sourcing in the dpoisLocal_normal_2() function that we will need to run the MCMC
#source("dpoisLocal_normal.R")

# Sourcing in the function that we'll need to run the MCMC
source("MCMC_Function_Inhomogeneous.R")
library("spatstat")

### Generating the value of our chosen covariate for each pixel (as we are assuming an inhomgeneous Poisson process)
## First, need to load 'mona_df' -- this contains the covariate values that we want to use
#load("../output/mona_inputs.RData")
load("mona_inputs.RData") # For NeSI
# We want to subset the 'Dgood' column from the resulting data frame, as this contains the values for our chosen covariate here. We also are subsetting
# the x- and y-coordinate columns (these give the pixel centres that correspond to each covariate value)
mona.densities = mona_df[,c("x", "y", "Dblur_bigD")]
# Lastly, we want to reorder our 'mona.densities' data frame, so that the order of the pixels in the data frame matches the order of the pixels in our 'pixel.centres' object (generated by the centres() function). Currently, both objects have the pixels in the 'opposite' order to each other -- making the order of the pixels the same in both objects means that it'll be easier to write our NIMBLE model (as both objects can be subsetted using the same indices). To do this reordering, we need to reverse the order of the 'y' column only - so we split up data frame into groups based on the y-values, and then re-join the result into a data frame where the smallest y-values occur in the first rows and the largest ones are in the last rows of the data frame. We do this below.
split = split(mona.densities, mona.densities$y)
mona.densities = do.call("rbind", split)
# And now that we are sure of the way in which the pixels are numbered, can remove the x and y-coordinate columns, so that we are now left with a density vector only, which we will then use with NIMBLE!
dblur = mona.densities[,"Dblur_bigD"]

## Generating 'pixel.info' object we need
# Pixel centres in the map region
library("spatstat")
# Function
centres = function(xrange, yrange, x.pixels, y.pixels) {
  window.2 = owin(xrange=xrange, yrange=yrange)
  points = gridcentres(window.2, x.pixels, y.pixels)
  centres = as.matrix(cbind(points$x, points$y))
  centres
}
pixel.centres = centres(xrange=c(0.5, 50.5), yrange=c(0.5, 50.5), x.pixels=50, y.pixels=50)
pixel.info = cbind(pixel.centres, dblur)

ch7f.sample = run.MCMC.inhom(data.ch7f, pixel.info=pixel.info, pixel.area=1, M=9000, inits.vec=c(10, 4, 0),  n.iter=100000)
save(ch7f.sample, file="ch7f.RData")
